// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-mocha/gulp-mocha.d.ts
declare module "gulp-mocha" {
    function mocha(setupOptions?: MochaSetupOptions): NodeJS.ReadWriteStream;
    namespace mocha {}
    export = mocha;
}
